CC = gcc

CFLAGS = -pthread -g -std=gnu99 -O1 -Wall
LDFLAGS = -lrt -lpthread

SOURCES = app.c display.c console_info.c socket_rocket.c devices_list.c pixel.c mzapo_phys.c mzapo_parlcd.c font_rom8x16.c
TARGET_EXE = app

OBJECTS += $(filter %.o,$(SOURCES:%.c=%.o))

#$(warning OBJECTS=$(OBJECTS))

LINKER = $(CC)
LDFLAGS += $(CFLAGS) $(CPPFLAGS)

%.o:%.c
	$(CC) $(CFLAGS) -c $<

all: $(TARGET_EXE)

$(TARGET_EXE): $(OBJECTS)
	$(LINKER) $(LDFLAGS) -L. $^ -o $@

.PHONY : dep all run

dep: depend

depend: $(SOURCES) *.h
	echo '# autogenerated dependencies' > depend
ifneq ($(filter %.c,$(SOURCES)),)
	$(CC) $(CFLAGS) $(CPPFLAGS) -w -E -M $(filter %.c,$(SOURCES)) \
	  >> depend
endif

clean:
	rm -f *.o *.a $(OBJECTS) $(TARGET_EXE) depend

-include depend
